package com.customerdetails.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;      // Generates getter methods for all fields
import lombok.Setter;      // Generates setter methods for all fields

/**
 * JPA entity representing a customer record.
 * This class is mapped to the "Customers" table in the database.
 */
@Entity
@Table(name = "Customers")   // Maps this entity to the Customers database table
@Getter                      // Lombok generates getter methods for all fields
@Setter                      // Lombok generates setter methods for all fields
@AllArgsConstructor          // Lombok generates a constructor with all fields as parameters
public class Customer {

    /**
     * Primary key of the customer.
     * The value is automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long customerId;

    //Customer's first name.
    private String firstName;

    //Customer's last name.
    private String lastName;

    //Customer's email address.
    private String emailAddress;

    //Customer's physical or residential address.
    private String physicalAddress;
}